sudo: false
language: scala
scala:
  - 2.12.12
  - 2.13.3
  
jdk: openjdk8

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
  
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- rm -f $HOME/.ivy2/.sbt.ivy.lock

script: sbt ";++2.12.12 publishLocal; ++$TRAVIS_SCALA_VERSION test"

notifications:
  email:
    recipients:
      - "mrzeznicki@iterato.rs"
  on_success: change
  on_failure: always
  on_error: always
  on_start: never
  on_cancel: never

